jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-Multi-GPU'
    JobName: 'Linux_CI_Multi_GPU_Dev'
    BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory) -x "--enable_multi_device_test"'
    DoNugetPack:  'false'
    ArtifactName: 'drop-linux'
