parameters:
  packageFolder: $(Build.ArtifactStagingDirectory)

steps:
- task: CmdLine@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'Extract version number from the NuPkg file, Windows VMs'
  inputs:
    workingDirectory: '${{ parameters.packageFolder }}'
    script: |
      SETLOCAL EnableDelayedExpansion
      FOR /R %%i IN (Microsoft.ML.OnnxRuntime*.nupkg) do (
        set filename=%%~ni
        set ortversion=!filename:~25!
        IF "!filename:~25,3!"=="Gpu" (
          set ortversion=!filename:~29!
        ) ELSE (
          IF "!filename:~25,5!"=="MKLML" (
            set ortversion=!filename:~31!
          )
        ) 

        @echo ortversion is !ortversion!
        @echo ##vso[task.setvariable variable=NuGetPackageVersionNumber;]!ortversion!
      )

- task: CmdLine@2
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
  displayName: 'Extract version number from the NuPkg file, Unix VMs'
  inputs:
    workingDirectory: '${{ parameters.packageFolder }}'
    script: |
      filenamewithext=$(ls Microsoft.ML.OnnxRuntime*.nupkg)
      filename=${filenamewithext%.*}
      ortversion=${filename:25}
      if [ "${filename:25:3}" = "Gpu" ]
      then
         ortversion=${filename:29}
      elif [ "${filename:25:5}" = "MKLML" ]
      then
         ortversion=${filename:31}
      fi
      echo "##vso[task.setvariable variable=NuGetPackageVersionNumber;]$ortversion"
